trigger:
  branches:
    include:
      - develop

variables:
  DEV_DATABRICKS_HOST: 'https://<dev-databricks-instance>'
  QAS_DATABRICKS_HOST: 'https://<qas-databricks-instance>'
  PRO_DATABRICKS_HOST: 'https://<pro-databricks-instance>'
  DEV_DATABRICKS_TOKEN: $(DEV_DATABRICKS_TOKEN)
  QAS_DATABRICKS_TOKEN: $(QAS_DATABRICKS_TOKEN)
  PRO_DATABRICKS_TOKEN: $(PRO_DATABRICKS_TOKEN)
  NOTEBOOKS_PATH: '/Workspace/Notebooks'

stages:
  - stage: DEV
    jobs:
      - job: PublishToDEV
        displayName: 'Publicar no ambiente DEV'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              echo "Publicando notebooks no ambiente DEV"
              curl -n -X POST "$(DEV_DATABRICKS_HOST)/api/2.0/workspace/import" \
                -H "Authorization: Bearer $(DEV_DATABRICKS_TOKEN)" \
                -F path=$(NOTEBOOKS_PATH)/DEV/ \
                -F format=SOURCE \
                -F language=PYTHON \
                -F content=@notebooks.zip
            displayName: 'Publicar notebooks no DEV'