trigger:
  branches:
    include:
      - develop
      - main
  paths:
    include:
      - 'notebooks/*'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: CIJob
        displayName: "Countinuous Integration Steps"
        steps:
          - checkout: self
            clean: true